import React from "react";
import { Copyright } from "lucide-react";
import MenuBar from "@/components/menu";
import type {JSX} from "react";
import type { Metadata } from "next";
import Link from "next/link";

const others = [
    {
        title: "Matcha Lover",
        image: "/Images/matcha.jpg",
        position: "left",
    },
    {
        title: "Traveler",
        image: "/Images/travel.jpg",
        position: "right",
    },
    {
        title: "Happy-Go-Lucky",
        image: "/Images/happy.jpg",
        position: "left",
    },
];

export const metadata: Metadata = {
    title: "Others",
    description: "Generated by create next app",
};

export default function Others(): JSX.Element {
    return (
        <div className="bg-white flex flex-col items-center w-full min-h-screen px-4">
            <div className="w-full max-w-[1430px] relative py-6">

                <MenuBar />

                {/* Vertical Sakinah text */}
                <Link href = "/"
                    className="absolute h-[168px] top-[80px] left-[20px] -rotate-90 ">
                <div className="[font-family: 'Aoboshi_One-Regular',Helvetica] font-normal text-[#ff009d] text-2xl xl:text-4xl">
                    SAKINAH
                </div>
                </Link>

                {/* Vertical line */}
                <div className="w-px h-[1500px] top-0 left-[50px] absolute bg-black"/>

                {/* Horizontal line */}
                <div className="w-[1500px] h-px top-15 left-[-40px] absolute bg-black"/>

                {/* Other heading */}
                <div className="text-center text-[#ff009d] text-4xl sm:text-5xl md:text-5xl font-normal tracking-[10px] [font-family: 'Aoboshi_One-Regular', Helvetica]">
                    OTHERS ABOUT ME
                </div> 

                {/* Other list */}
                <div className="mt-10 flex flex-col gap-10">
                    {others.map((item) => (
                        <div 
                        key={item.title}
                        className={`flex flex-col ${
                            item.position === "left" ? "md:flex-row md:gap-12" : "md:flex-row-reverse md:gap-12"
                        } items-center gap-6`}
                        >
                                
                                <div className="ml-30 w-full md:w-1/2 h-[200px] md:h-[400px] rounded-lg overflow-hidden">
                                        <div 
                                        className="w-full h-full bg-cover bg-center"
                                        style={{ backgroundImage: `url(${item.image})`}}
                                        />
                                    </div>
                                    
                                    <div className="text-center md:text-center w-full md:w-1/2">
                                        <div className="font-medium text-black text-2xl md:text-3xl leading-tight font-[Inter-Medium]">
                                            {item.title}
                                        </div>
                                    </div>

                            </div>
                            
                    ))}
                </div>
                </div>

                {/* Footer */}
                <div className="mt-16 flex justify-center items-center">
                    <div className="flex items-center gap-2 text-sm md:text-lg [font-family: 'Inter-SemiBold',Helvetica] font-semibold text-black text-2xl text-center">
                        <span>2025 by Sakinah</span>
                        <Copyright className="w-6 h-6" />
                    </div>
                </div>
                </div>
    )
}