
import React from "react";
import type { JSX } from "react";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function FrontPage(): JSX.Element {

  // Portfolio images
  const portfolioImages = [
    {
      src: "/Images/about.jpeg",
      alt: "Whatsapp image",
    },
    {
      src: "/Images/skills.jpg",
      alt: "Element best skillshare",
    },
    {
      src: "/Images/organization.jpeg",
      alt: "Organization",
    },
    {
      src: "/Images/others.jpeg",
      alt: "Others",
    },
  ];

  return (
    <div className="bg-white flex flex-col items-center min-h-screen px-4 py-8 sm:py-12">
        {/* Portfolio Images Section */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 w-full max-w-[1440px]">
          {portfolioImages.map((image, index) => (
            <img
              key={index}
              className={"w-full h-52 sm:h-60 md:h-72 lg:h-96 object-cover rounded-lg bg-gray-200 "}
              alt={image.alt}
              src={image.src}
              />
          ))}
        </div>

        {/* Portfolio Title Section */}
        <div className="text-center mt-12">
          <div className="font-[Aoboshi_One-Regular] text-4xl sm:text-5xl md:text-6xl lg:text-7xl text-[#ff009d] tracking-wide ">
            SAKINAH
          </div>
        </div>

        <div className="mt-6">
          <Link href="/about">
          <button
            className="px-6 py-3 rounded-full bg-[#ff009d] text-white text-lg sm:text-xl font-medium hover:bg-black transition-colors duration-300">
            <span 
              className="text-xl text-white font-medium "
              style={{ fontFamily: "'League Spartan-Medium', Helvetica"}}
              >
                Continue
              </span>
          </button>
          </Link>
        </div>
      </div>
  );
}