
import React from "react";
import type {JSX} from "react";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function FrontPage(): JSX.Element {

  // Portfolio images
  const portfolioImages = [
    {
      src: "/Images/about.jpeg",
      alt: "Whatsapp image",
    },
    {
      src: "/Images/skills.jpg",
      alt: "Element best skillshare",
    },
    {
      src: "/Images/organization.jpeg",
      alt: "Organization",
    },
    {
      src: "/Images/others.jpeg",
      alt: "Others",
    },
  ];

  return (
    <div className="bg-white flex flex-col items-center min-h-screen px-4 py-6">

        {/* Portfolio Images Section */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 w-full max-w-[1440px]">
          {portfolioImages.map((image, index) => (
            <img
              key={index}
              className={"w-full h-60 md:h-[400px] object-cover rounded-lg bg-gray-200"}
              alt={image.alt}
              src={image.src}
              />
          ))}
        </div>

        {/* Portfolio Title Section */}
        <div className="flex flex-col items-center text-center mt-12">
          <div className="font-[Aoboshi_One-Regular] text-5xl md:text-7xl text-[#ff009d] tracking-wider ">
            SAKINAH
          </div>
        </div>

        <div className="flex justify-center">
          <Link href="/about">
          <button
            className="w-[100px] h-[50px] rounded-[30px] bg-[#ff009d] mt-4 flex items-center justify-center active:bg-black transition-colors">
            <span 
              className="text-xl text-white font-medium "
              style={{ fontFamily: "'League Spartan-Medium', Helvetica"}}
              >
                Continue
              </span>
          </button>
          </Link>
        </div>
      </div>
  );
}